apiVersion: apps/v1
kind: Deployment
metadata:
  name: testtwo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testtwo
  template:
    metadata:
      labels:
        app: testtwo
    spec:
      containers:
        - name: test2
          image: pranv21/test2
