apiVersion: apps/v1
kind: Deployment
metadata:
  name: testone-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testone
  template:
    metadata:
      labels:
        app: testone
    spec:
      containers:
        - name: test1
          image: pranv21/test
