apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: pranv21/full-client
