apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: pranv21/full-server
