apiVersion: v1
kind: Service
metadata:
  name: testone-service
spec:
  type: NodePort
  selector:
    app: testone
  ports:
    - name: testone
      protocol: TCP
      port: 5000
      targetPort: 5000
