apiVersion: v1
kind: Service
metadata:
  name: testtwo-service
spec:
  type: NodePort
  selector:
    app: testtwo
  ports:
    - name: testtwo
      protocol: TCP
      port: 6000
      targetPort: 6000
