apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # Only one pod that is associated with this pvc can read and write to the persistent volume
  resources:
    requests:
      storage: 2Gi
# storageClassName for cloud pv implementation
