apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template: # Specifies template for each individual pod that this deployment creates and maintains
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: pranv21/tickets4all-auth
          env:
            - name: environment
              value: production
            - name: POSTGRES_HOST
              value: postgres-clusterip-service
            - name: POSTGRES_USER
              value: postgres # Default admin user
            - name: POSTGRES_PORT
              value: "5432" # Must be string
            - name: POSTGRES_DATABASE
              value: postgres # Default database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-vars
                  key: POSTGRES_PASSWORD # Secret can store several key-value pair
