apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 # Need extra configuration to have multiple pods access and r/w to same persistent volume
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes: # Asks kubernetes for pv using the pvc template
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres:14-alpine # Default process expose port 5432 for db access
          volumeMounts: # Use the pv from kubernetes for storage
            - name: postgres-volume # Must match vloume name
              mountPath: /var/lib/postgresql/data # Storage location for data in postgres
              subPath: postgres # Postgres specifc option
          env:
            - name: POSTGRES_PASSWORD # Overwrites defualt password
              valueFrom:
                secretKeyRef:
                  name: env-vars
                  key: POSTGRES_PASSWORD
