apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
spec:
  selector:
    app: auth # Selects pod to service by matching key-value pair
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000
