apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip-service
spec:
  selector:
    app: postgres # Selects pod to service by matching key-value pair
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
